<?php
/**
 * @file
 * Main hooks.
 */

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function coh_custom_forms_islandora_xml_form_builder_form_associations() {
  return array(
    'coh_artwork_form' => array(
      'content_model' => 'islandora:sp_large_image_cmodel',
      'form_name' => 'City of Hope MODS Metadata',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended_strict.xsl',
      'template' => FALSE,
    ),
    'coh_pdf_form' => array(
      'content_model' => 'islandora:sp_pdf',
      'form_name' => 'City of Hope MODS Metadata',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended_strict.xsl',
      'template' => FALSE,
    ),
    'coh_audio_form' => array(
      'content_model' => 'islandora:sp-audioCModel',
      'form_name' => 'City of Hope MODS Metadata',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended_strict.xsl',
      'template' => FALSE,
    ),
    'coh_basic_image_form' => array(
      'content_model' => 'islandora:sp_basic_image',
      'form_name' => 'City of Hope MODS Metadata',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended_strict.xsl',
      'template' => FALSE,
    ),
    'coh_compound_form' => array(
      'content_model' => 'islandora:compoundCModel',
      'form_name' => 'City of Hope MODS Metadata',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended_strict.xsl',
      'template' => FALSE,
    ),
    'coh_book_form' => array(
      'content_model' => 'islandora:bookCModel',
      'form_name' => 'City of Hope MODS Metadata',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended_strict.xsl',
      'template' => FALSE,
    ),
    'coh_video_form' => array(
      'content_model' => 'islandora:sp_videoCModel',
      'form_name' => 'City of Hope MODS Metadata',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended_strict.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function coh_custom_forms_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'coh_custom_forms');
  return array(
    'City of Hope MODS Metadata' => array(
      'form_file' => "$module_path/xml/coh_mods.xml",
    ),
  );
}
